### ISSUE TITLE
Oddity with graphing (1-x^2)^0.5

### ISSUE THREAD

**Issue by SigmaEpsilonChi** [FlorianRappl/YAMP#13]
Graphing (1-x^2)^0.5 yields a strange incorrect value at x=-1 (should return 0, instead returns ~0.7)

**Comment by FlorianRappl** [comment]
![image](https://cloud.githubusercontent.com/assets/1766191/11286039/f1e3813e-8f12-11e5-9254-79e04698b2a7.png)

Yep, seems odd. From a quick first evaluation I'd say the value of `(1-(-1)^2)` is not `0`, but something that behaves oddly with the power implementation (behaving like it would be `-i`). A first guess is that the power function has a bug. I'll investigate and release a bug fix!

Thanks for the report and also the nice talk earlier.

**Comment by FlorianRappl** [comment]
So obviously the whole algorithm is (mathematically) quite correct, however, double precision seems to be just too imprecise for handling these kinds of things.

The initial angle `-pi` was multiplied with the factor `2.0`, which, however, turned out to be finite (but very small), i.e., `sin(-2pi) != 0`. The new tolerance only affects imaginary parts and should be well set for most usages.

There is probably a numerically more stable algorithm to take complex numbers to complex powers, but for the moment this seems to do the job. I'll update the NuGet package as soon as possible.
